version: '2'
services:
  smartcossiolbackend-app:
    image: smartcossiolbackend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://smartcossiolbackend-mariadb:3306/smartcossiolbackend
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  smartcossiolbackend-mariadb:
    extends:
      file: mariadb.yml
      service: smartcossiolbackend-mariadb
